name : Build 
on : 
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master
    
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name : go mod
      run : go mod tidy
    - name: Build
      run: go build -v -o cicd server.go
    - uses: actions/upload-artifact@v3
      with:
        name: build-cicd
        path: cicd
  
  uploadAndDeploy :
    needs : test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-cicd
          
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../.ssh/private.key
          sudo chmod 600 ../.ssh/private.key
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SECRET_KEY}}
          SSH_KEY_PATH: ${{ github.workspace }}/../.ssh/private.key
          
      - name : sftp connect
        run : sftp -i $SSH_KEY_PATH adam@34.121.123.185 
        env :
          SSH_KEY_PATH: ${{ github.workspace }}/../.ssh/private.key

      - name : upload file
        run : put cicd
      - name : exit sftp
        run : exit
      - name : ssh connect
        run : ssh -i $SSH_KEY_PATH adam@34.121.123.185 
        env :
          SSH_KEY_PATH: ${{ github.workspace }}/../.ssh/private.key
      - name : deploy 
        run : ./cicd
      
      
