name : Build 
on : 
  workflow_dispatch:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master
    
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name : go mod
      run : go mod tidy
    - name: Build
      run: go build -v -o cicd server.go
    - uses: actions/upload-artifact@v3
      with:
        name: build-cicd
        path: cicd
  
  uploadAndDeploy :
    needs : test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-cicd
          
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SECRET_KEY}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          
      - name : scp transfer file 
        run : scp -i $SSH_KEY_PATH ./cicd adam@34.121.123.185:/home/adam
        env :
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name : ssh connect and deploy
        run : ssh -i $SSH_KEY_PATH adam@34.121.123.185 'chmod 777 cicd && chown root cicd && ./cicd'
        env :
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
 
      
      
