name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: go mod
        run: go mod tidy
      - name: Build
        run: go build -v -o cicd server.go
      - uses: actions/upload-artifact@v3
        with:
          name: build-cicd
          path: cicd

  uploadAndDeploy:
    needs: test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-cicd
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible-playbook.yml
          directory: ./
          key: ${{secrets.SECRET_KEY}}
          known_hosts: ${{secrets.SSH_KNOWN_HOSTS}}
          options: |
            -i inventory.yaml
            -u adam
